name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to'
        required: true

jobs:

  bump-version:
    uses: stellar/actions/.github/workflows/rust-bump-version.yml@658eb90cea1d328449cb470d752bc2b6411aed0a
    with:
      version: ${{ inputs.version }}
