name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to'
        required: true

jobs:

  bump-version:
    uses: stellar/actions/.github/workflows/rust-bump-version.yml@500fdd56ab41d7bb08a29680757d6695d5947931
    with:
      version: ${{ inputs.version }}
