name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to'
        required: true

jobs:

  bump-version:
    uses: stellar/actions/.github/workflows/rust-bump-version.yml@e462f32a74e739fc14af5d126bece0bb889784ae
    with:
      version: ${{ inputs.version }}
